// <auto-generated />
using GiuaKy;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GiuaKy.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20250328090019_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GiuaKy.Models.DiemThi", b =>
                {
                    b.Property<int>("MaSV")
                        .HasColumnType("int");

                    b.Property<string>("MaMH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<float>("DiemThi1")
                        .HasColumnType("real");

                    b.Property<float>("DiemThi2")
                        .HasColumnType("real");

                    b.HasKey("MaSV", "MaMH");

                    b.HasIndex("MaMH");

                    b.ToTable("DiemThis");
                });

            modelBuilder.Entity("GiuaKy.Models.MonHoc", b =>
                {
                    b.Property<string>("MaMH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte>("SoTC")
                        .HasColumnType("tinyint");

                    b.Property<string>("TenMH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMH");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("GiuaKy.Models.Sinhvien", b =>
                {
                    b.Property<int>("MaSV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSV"));

                    b.Property<int>("Gioitinh")
                        .HasColumnType("int");

                    b.Property<string>("HinhSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hodem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ngaysinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Noisinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSV");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("GiuaKy.Models.DiemThi", b =>
                {
                    b.HasOne("GiuaKy.Models.MonHoc", "MonHoc")
                        .WithMany("DiemThis")
                        .HasForeignKey("MaMH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GiuaKy.Models.Sinhvien", "SinhVien")
                        .WithMany("DiemThis")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("GiuaKy.Models.MonHoc", b =>
                {
                    b.Navigation("DiemThis");
                });

            modelBuilder.Entity("GiuaKy.Models.Sinhvien", b =>
                {
                    b.Navigation("DiemThis");
                });
#pragma warning restore 612, 618
        }
    }
}
